### ISSUE TITLE
restaring VLC after password configutarion does'nt work

### ISSUE THREAD

**Issue by amirlevy1010** [ophirhan/cnsr-vlc-viewer-addon#109]
the same menu of asking to configure a password comes up after pre-defining it and restarting VLC
<img width="365" alt="Capture" src="https://user-images.githubusercontent.com/66698414/122914610-7ac6bd00-d363-11eb-9ca9-19beb8e31970.PNG">

**Comment by alonShevach** [comment]
Posted a PR, please check if it fixes the bug
