### ISSUE TITLE
While loop on line 163 does not do what intended. runs only once.

### ISSUE THREAD

**Issue by alonShevach** [ophirhan/cnsr-vlc-viewer-addon#123]
In my opinion we can remove this loop, i understood it's purpose to prevent the sleep while a tag is running.
Currently the loop runs once, like an if statement. some fixes needs to be made so it will run more than once. but i have noticed that if those changes are made, the video is stuck, the time doesn't update properly, and eventually vlc crashes.

would like to hear your thoughts about that, maybe I am missing something.

**Comment by ophirhan** [comment]
in the loop we execute the tag that was returned from get_current_tag when we woke up.
We then send that tag to the get_current_tag- if that tag is not skip we return the next tag.
We then enter the loop again if that next tag start_time < current_time meaning if they started at the same time or we jumped into an overlapping section of tags :grin:
