### ISSUE TITLE
problem with viewing the dialog in macOS

### ISSUE THREAD

**Issue by liatweissman** [ophirhan/cnsr-vlc-viewer-addon#34]
Hi,
I'm using macOS and I have a bug in viewing the category selection and as a result, use the add-on (the last 2 tags are not displayed and the apply button is not displayed - so I can not use the extension as a mac user)

this is what I see:
<img width="880" alt="צילום מסך 2021-06-12 ב-20 00 15" src="https://user-images.githubusercontent.com/44327289/121785058-49f6c300-cbc0-11eb-877c-c5788d47a869.png">

**Comment by eyal1889** [comment]
thanks for that! 
we clearly missed that one, and we are working on it!

**Comment by ophirhan** [comment]
Thank you for the feedback!
I propose we try re implementing this dialog with  HTML.
This way we might also be able to load previous preferences from the disk

**Comment by ishayhil** [comment]
added task to https://github.com/ophirhan/cnsr-vlc-viewer-addon/projects/1
