### ISSUE TITLE
overlapping timestamps cause the end time to add up

### ISSUE THREAD

**Issue by Gal-Tch** [ophirhan/cnsr-vlc-viewer-addon#93]
example:  
if we set 'violence' and 'verbal abuse' to 'skip', the following cnsr file should skip from 00:00:00,000 to 00:00:010,000 .
cnsr_file:

> 00:00:00,000 - 00:00:10,000; 1
> 00:00:00,000 - 00:00:10,000; 2

instead, the video skips from  00:00:00,000 to 00:00:020,000

**Comment by eyal1889** [comment]
well, the times arent good in the end time. why 010 and not just 10 in the seconds?
we dont handle bad input right now so that can be the problem. try it with good cnsr file

**Comment by Gal-Tch** [comment]
Sorry, did not notice the extra 0. I tested again with valid input that actually makes sense for user to use.

**Comment by eyal1889** [comment]
So? Did it work?

**Comment by Gal-Tch** [comment]
The issue still remains, I updated this issue with the new cnsr file I tested
